//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSSAgregator.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedSource
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Url { get; set; }
        public bool Public { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int FeedCategoryId { get; set; }
    
        public virtual User User { get; set; }
        public virtual FeedCategory FeedCategory { get; set; }
    }
}
