//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSSAgregator.Database.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedCategory
    {
        public FeedCategory()
        {
            this.FeedSources = new HashSet<FeedSource>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Public { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int UserId { get; set; }
    
        public virtual ICollection<FeedSource> FeedSources { get; set; }
        public virtual User User { get; set; }
    }
}
