//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSSAgregator.Database.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.FeedSources = new HashSet<FeedSource>();
            this.FeedCategories = new HashSet<FeedCategory>();
        }
    
        public int Id { get; set; }
        public string Roles { get; set; }
        public string Username { get; set; }
        public string EmailAddress { get; set; }
        public string FacebookId { get; set; }
        public string TwitterId { get; set; }
        public string GoogleId { get; set; }
        public System.DateTime SignUpDate { get; set; }
    
        public virtual ICollection<FeedSource> FeedSources { get; set; }
        public virtual ICollection<FeedCategory> FeedCategories { get; set; }
    }
}
